title: Lucas A Enrich # your name (or website title) here
logo: "/images/pp.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Econometría, Machine Learning, Data Science 
  
  <br><br>
  <a href="https://www.linkedin.com/in/lucas-ariel-enrich-a7320a93/"><img src = l.png></a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
